name: E2E on Chrome headed
on: 
  push:
    branches: 
      - main
      
  #Set your workflow to run every day of the week from Monday to Friday at 2:00 UTC
  schedule:
   - cron: "0 3 * *  1-5"
 
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          spec: '**/*.feature'
          #still running some tests here
          browser: chrome
          record: true
        env:
           # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
           # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
