name: E2E on Chrome headed
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headed: true
          record: true
        env:
           # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: $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
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: $059b9ae0-a13a-4ce5-9635-407daaff6a5f
           # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: $3xmw3x
